BEGIN;

DROP TABLE picture CASCADE;

DROP TABLE category CASCADE;

DROP TABLE account CASCADE;

DROP TABLE article CASCADE;

DROP TABLE article_picture CASCADE;

DROP TABLE article_category CASCADE;

DROP TABLE rent_proposal CASCADE;

COMMIT;